# Generated by Django 5.1.5 on 2025-01-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=25)),
            ],
        ),
    ]
