# Generated by Django 5.1.5 on 2025-01-22 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapps', '0003_alter_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_on_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_on_suspicious_login',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255)),
                ('device_os', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('location_city', models.CharField(blank=True, max_length=255)),
                ('location_country', models.CharField(blank=True, max_length=255)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_datetime'],
            },
        ),
    ]
