# Generated by Django 5.1.5 on 2025-01-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapps', '0006_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
