# Generated by Django 5.1.5 on 2025-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapps', '0007_customuser_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='backup_codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
